services:
  cache:
    build:
      context: meli-cache-services
      dockerfile: Dockerfile
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: meli-challenge
    networks:
      challengeNet:
        ipv4_address: 10.5.0.5
    ports: 
      - "8081:8081"    
  proxy:
    build:
      context: meli-api-proxy
      dockerfile: Dockerfile
    depends_on:
      cache:
        condition: service_started
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: meli-challenge
    ports: 
      - "8080:8080"  
    expose: 
      - "8080"  
    networks:
      challengeNet:
        ipv4_address: 10.5.0.6
networks:
  challengeNet:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1